# Default values for hello-world.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: vikas1412/gcp_hello_world_app
  pullPolicy: Always
  imageTag: v2.0

service:
  type: LoadBalancer
  port: 8080

config:
  message: "Hello, World!"

secret:
  username: "admin"
  password: "password123"

ingress:
  enabled: false

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50


