apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hello-world.fullname" . }}
  labels:
    app: {{ include "hello-world.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "hello-world.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "hello-world.name" . }}
    spec:
      replicaes: 2
      containers:
        - name: {{ include "hello-world.name" . }}
          image: "{{ .Values.image.repository }}:latest"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: HELLO_MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "hello-world.fullname" . }}
                  key: message
            - name: TEST_MESSAGE
              value: Sample test value
            - name: APP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "hello-world.fullname" . }}-secret
                  key: username
            - name: APP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "hello-world.fullname" . }}-secret
                  key: password
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
